language: python

python:
  - "2.6"
  - "2.7"
# So far python-ldap doesn't support python 3
#  - "3.2"
#  - "3.3"

env:
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6

# command to install dependencies
install:
  - "pip install -q Django==$DJANGO_VERSION"
  - "pip install -r requirements.txt"

# command to run tests
script: 
  - python tests/testproject/manage.py test ldapidp
